// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -source=./interfaces.go -destination=./mock/storage.go -package=storagemock
//

// Package storagemock is a generated GoMock package.
package storagemock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/smanhack/gophkeeper/internal/server/model"
)

// MockAccountServerStorage is a mock of AccountServerStorage interface.
type MockAccountServerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServerStorageMockRecorder
	isgomock struct{}
}

// MockAccountServerStorageMockRecorder is the mock recorder for MockAccountServerStorage.
type MockAccountServerStorageMockRecorder struct {
	mock *MockAccountServerStorage
}

// NewMockAccountServerStorage creates a new mock instance.
func NewMockAccountServerStorage(ctrl *gomock.Controller) *MockAccountServerStorage {
	mock := &MockAccountServerStorage{ctrl: ctrl}
	mock.recorder = &MockAccountServerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountServerStorage) EXPECT() *MockAccountServerStorageMockRecorder {
	return m.recorder
}

// FindByCredentials mocks base method.
func (m *MockAccountServerStorage) FindByCredentials(ctx context.Context, user model.Account) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCredentials", ctx, user)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCredentials indicates an expected call of FindByCredentials.
func (mr *MockAccountServerStorageMockRecorder) FindByCredentials(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCredentials", reflect.TypeOf((*MockAccountServerStorage)(nil).FindByCredentials), ctx, user)
}

// RemoveAccount mocks base method.
func (m *MockAccountServerStorage) RemoveAccount(ctx context.Context, user model.Account) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccount", ctx, user)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAccount indicates an expected call of RemoveAccount.
func (mr *MockAccountServerStorageMockRecorder) RemoveAccount(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccount", reflect.TypeOf((*MockAccountServerStorage)(nil).RemoveAccount), ctx, user)
}

// StoreAccount mocks base method.
func (m *MockAccountServerStorage) StoreAccount(ctx context.Context, user model.Account) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAccount", ctx, user)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreAccount indicates an expected call of StoreAccount.
func (mr *MockAccountServerStorageMockRecorder) StoreAccount(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAccount", reflect.TypeOf((*MockAccountServerStorage)(nil).StoreAccount), ctx, user)
}

// MockCategoryServerStorage is a mock of CategoryServerStorage interface.
type MockCategoryServerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryServerStorageMockRecorder
	isgomock struct{}
}

// MockCategoryServerStorageMockRecorder is the mock recorder for MockCategoryServerStorage.
type MockCategoryServerStorageMockRecorder struct {
	mock *MockCategoryServerStorage
}

// NewMockCategoryServerStorage creates a new mock instance.
func NewMockCategoryServerStorage(ctrl *gomock.Controller) *MockCategoryServerStorage {
	mock := &MockCategoryServerStorage{ctrl: ctrl}
	mock.recorder = &MockCategoryServerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryServerStorage) EXPECT() *MockCategoryServerStorageMockRecorder {
	return m.recorder
}

// ListCategories mocks base method.
func (m *MockCategoryServerStorage) ListCategories(ctx context.Context) ([]model.DataCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]model.DataCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockCategoryServerStorageMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockCategoryServerStorage)(nil).ListCategories), ctx)
}

// MockDataVaultServerStorage is a mock of DataVaultServerStorage interface.
type MockDataVaultServerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDataVaultServerStorageMockRecorder
	isgomock struct{}
}

// MockDataVaultServerStorageMockRecorder is the mock recorder for MockDataVaultServerStorage.
type MockDataVaultServerStorageMockRecorder struct {
	mock *MockDataVaultServerStorage
}

// NewMockDataVaultServerStorage creates a new mock instance.
func NewMockDataVaultServerStorage(ctrl *gomock.Controller) *MockDataVaultServerStorage {
	mock := &MockDataVaultServerStorage{ctrl: ctrl}
	mock.recorder = &MockDataVaultServerStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataVaultServerStorage) EXPECT() *MockDataVaultServerStorageMockRecorder {
	return m.recorder
}

// FetchData mocks base method.
func (m *MockDataVaultServerStorage) FetchData(ctx context.Context, secret model.DataRecord) (model.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchData", ctx, secret)
	ret0, _ := ret[0].(model.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchData indicates an expected call of FetchData.
func (mr *MockDataVaultServerStorageMockRecorder) FetchData(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchData", reflect.TypeOf((*MockDataVaultServerStorage)(nil).FetchData), ctx, secret)
}

// QueryDataByCategory mocks base method.
func (m *MockDataVaultServerStorage) QueryDataByCategory(ctx context.Context, secretType model.DataCategory, user model.Account) ([]model.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryDataByCategory", ctx, secretType, user)
	ret0, _ := ret[0].([]model.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryDataByCategory indicates an expected call of QueryDataByCategory.
func (mr *MockDataVaultServerStorageMockRecorder) QueryDataByCategory(ctx, secretType, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryDataByCategory", reflect.TypeOf((*MockDataVaultServerStorage)(nil).QueryDataByCategory), ctx, secretType, user)
}

// RemoveData mocks base method.
func (m *MockDataVaultServerStorage) RemoveData(ctx context.Context, secret model.DataRecord) (model.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveData", ctx, secret)
	ret0, _ := ret[0].(model.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveData indicates an expected call of RemoveData.
func (mr *MockDataVaultServerStorageMockRecorder) RemoveData(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveData", reflect.TypeOf((*MockDataVaultServerStorage)(nil).RemoveData), ctx, secret)
}

// StoreData mocks base method.
func (m *MockDataVaultServerStorage) StoreData(ctx context.Context, secret model.DataRecord) (model.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreData", ctx, secret)
	ret0, _ := ret[0].(model.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreData indicates an expected call of StoreData.
func (mr *MockDataVaultServerStorageMockRecorder) StoreData(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreData", reflect.TypeOf((*MockDataVaultServerStorage)(nil).StoreData), ctx, secret)
}

// UpdateData mocks base method.
func (m *MockDataVaultServerStorage) UpdateData(ctx context.Context, secret model.DataRecord, isForce bool) (model.DataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateData", ctx, secret, isForce)
	ret0, _ := ret[0].(model.DataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateData indicates an expected call of UpdateData.
func (mr *MockDataVaultServerStorageMockRecorder) UpdateData(ctx, secret, isForce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateData", reflect.TypeOf((*MockDataVaultServerStorage)(nil).UpdateData), ctx, secret, isForce)
}
