// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: secret_type.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataCategory_ListCategories_FullMethodName = "/proto.DataCategory/ListCategories"
)

// DataCategoryClient is the client API for DataCategory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataCategoryClient interface {
	ListCategories(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error)
}

type dataCategoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDataCategoryClient(cc grpc.ClientConnInterface) DataCategoryClient {
	return &dataCategoryClient{cc}
}

func (c *dataCategoryClient) ListCategories(ctx context.Context, in *CategoryListRequest, opts ...grpc.CallOption) (*CategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CategoryListResponse)
	err := c.cc.Invoke(ctx, DataCategory_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCategoryServer is the server API for DataCategory service.
// All implementations must embed UnimplementedDataCategoryServer
// for forward compatibility.
type DataCategoryServer interface {
	ListCategories(context.Context, *CategoryListRequest) (*CategoryListResponse, error)
	mustEmbedUnimplementedDataCategoryServer()
}

// UnimplementedDataCategoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataCategoryServer struct{}

func (UnimplementedDataCategoryServer) ListCategories(context.Context, *CategoryListRequest) (*CategoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedDataCategoryServer) mustEmbedUnimplementedDataCategoryServer() {}
func (UnimplementedDataCategoryServer) testEmbeddedByValue()                      {}

// UnsafeDataCategoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataCategoryServer will
// result in compilation errors.
type UnsafeDataCategoryServer interface {
	mustEmbedUnimplementedDataCategoryServer()
}

func RegisterDataCategoryServer(s grpc.ServiceRegistrar, srv DataCategoryServer) {
	// If the following call pancis, it indicates UnimplementedDataCategoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataCategory_ServiceDesc, srv)
}

func _DataCategory_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCategoryServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCategory_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCategoryServer).ListCategories(ctx, req.(*CategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataCategory_ServiceDesc is the grpc.ServiceDesc for DataCategory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataCategory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataCategory",
	HandlerType: (*DataCategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCategories",
			Handler:    _DataCategory_ListCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret_type.proto",
}
