// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: secret.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataVault_StoreData_FullMethodName           = "/proto.DataVault/StoreData"
	DataVault_FetchData_FullMethodName           = "/proto.DataVault/FetchData"
	DataVault_RemoveData_FullMethodName          = "/proto.DataVault/RemoveData"
	DataVault_UpdateData_FullMethodName          = "/proto.DataVault/UpdateData"
	DataVault_QueryDataByCategory_FullMethodName = "/proto.DataVault/QueryDataByCategory"
)

// DataVaultClient is the client API for DataVault service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataVaultClient interface {
	StoreData(ctx context.Context, in *StoreDataRequest, opts ...grpc.CallOption) (*StoreDataResponse, error)
	FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (*FetchDataResponse, error)
	RemoveData(ctx context.Context, in *RemoveDataRequest, opts ...grpc.CallOption) (*RemoveDataResponse, error)
	UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*UpdateDataResponse, error)
	QueryDataByCategory(ctx context.Context, in *QueryDataByCategoryRequest, opts ...grpc.CallOption) (*QueryDataByCategoryResponse, error)
}

type dataVaultClient struct {
	cc grpc.ClientConnInterface
}

func NewDataVaultClient(cc grpc.ClientConnInterface) DataVaultClient {
	return &dataVaultClient{cc}
}

func (c *dataVaultClient) StoreData(ctx context.Context, in *StoreDataRequest, opts ...grpc.CallOption) (*StoreDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDataResponse)
	err := c.cc.Invoke(ctx, DataVault_StoreData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataVaultClient) FetchData(ctx context.Context, in *FetchDataRequest, opts ...grpc.CallOption) (*FetchDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchDataResponse)
	err := c.cc.Invoke(ctx, DataVault_FetchData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataVaultClient) RemoveData(ctx context.Context, in *RemoveDataRequest, opts ...grpc.CallOption) (*RemoveDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDataResponse)
	err := c.cc.Invoke(ctx, DataVault_RemoveData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataVaultClient) UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*UpdateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDataResponse)
	err := c.cc.Invoke(ctx, DataVault_UpdateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataVaultClient) QueryDataByCategory(ctx context.Context, in *QueryDataByCategoryRequest, opts ...grpc.CallOption) (*QueryDataByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDataByCategoryResponse)
	err := c.cc.Invoke(ctx, DataVault_QueryDataByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataVaultServer is the server API for DataVault service.
// All implementations must embed UnimplementedDataVaultServer
// for forward compatibility.
type DataVaultServer interface {
	StoreData(context.Context, *StoreDataRequest) (*StoreDataResponse, error)
	FetchData(context.Context, *FetchDataRequest) (*FetchDataResponse, error)
	RemoveData(context.Context, *RemoveDataRequest) (*RemoveDataResponse, error)
	UpdateData(context.Context, *UpdateDataRequest) (*UpdateDataResponse, error)
	QueryDataByCategory(context.Context, *QueryDataByCategoryRequest) (*QueryDataByCategoryResponse, error)
	mustEmbedUnimplementedDataVaultServer()
}

// UnimplementedDataVaultServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataVaultServer struct{}

func (UnimplementedDataVaultServer) StoreData(context.Context, *StoreDataRequest) (*StoreDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreData not implemented")
}
func (UnimplementedDataVaultServer) FetchData(context.Context, *FetchDataRequest) (*FetchDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchData not implemented")
}
func (UnimplementedDataVaultServer) RemoveData(context.Context, *RemoveDataRequest) (*RemoveDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveData not implemented")
}
func (UnimplementedDataVaultServer) UpdateData(context.Context, *UpdateDataRequest) (*UpdateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateData not implemented")
}
func (UnimplementedDataVaultServer) QueryDataByCategory(context.Context, *QueryDataByCategoryRequest) (*QueryDataByCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDataByCategory not implemented")
}
func (UnimplementedDataVaultServer) mustEmbedUnimplementedDataVaultServer() {}
func (UnimplementedDataVaultServer) testEmbeddedByValue()                   {}

// UnsafeDataVaultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataVaultServer will
// result in compilation errors.
type UnsafeDataVaultServer interface {
	mustEmbedUnimplementedDataVaultServer()
}

func RegisterDataVaultServer(s grpc.ServiceRegistrar, srv DataVaultServer) {
	// If the following call pancis, it indicates UnimplementedDataVaultServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataVault_ServiceDesc, srv)
}

func _DataVault_StoreData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataVaultServer).StoreData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataVault_StoreData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataVaultServer).StoreData(ctx, req.(*StoreDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataVault_FetchData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataVaultServer).FetchData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataVault_FetchData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataVaultServer).FetchData(ctx, req.(*FetchDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataVault_RemoveData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataVaultServer).RemoveData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataVault_RemoveData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataVaultServer).RemoveData(ctx, req.(*RemoveDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataVault_UpdateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataVaultServer).UpdateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataVault_UpdateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataVaultServer).UpdateData(ctx, req.(*UpdateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataVault_QueryDataByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDataByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataVaultServer).QueryDataByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataVault_QueryDataByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataVaultServer).QueryDataByCategory(ctx, req.(*QueryDataByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataVault_ServiceDesc is the grpc.ServiceDesc for DataVault service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataVault_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataVault",
	HandlerType: (*DataVaultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreData",
			Handler:    _DataVault_StoreData_Handler,
		},
		{
			MethodName: "FetchData",
			Handler:    _DataVault_FetchData_Handler,
		},
		{
			MethodName: "RemoveData",
			Handler:    _DataVault_RemoveData_Handler,
		},
		{
			MethodName: "UpdateData",
			Handler:    _DataVault_UpdateData_Handler,
		},
		{
			MethodName: "QueryDataByCategory",
			Handler:    _DataVault_QueryDataByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret.proto",
}
