// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: secret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDataRequest) Reset() {
	*x = StoreDataRequest{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataRequest) ProtoMessage() {}

func (x *StoreDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataRequest.ProtoReflect.Descriptor instead.
func (*StoreDataRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{0}
}

func (x *StoreDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreDataRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StoreDataRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type NullableDeletedAt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*NullableDeletedAt_Null
	//	*NullableDeletedAt_Data
	Kind          isNullableDeletedAt_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableDeletedAt) Reset() {
	*x = NullableDeletedAt{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableDeletedAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDeletedAt) ProtoMessage() {}

func (x *NullableDeletedAt) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDeletedAt.ProtoReflect.Descriptor instead.
func (*NullableDeletedAt) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{1}
}

func (x *NullableDeletedAt) GetKind() isNullableDeletedAt_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *NullableDeletedAt) GetNull() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*NullableDeletedAt_Null); ok {
			return x.Null
		}
	}
	return structpb.NullValue(0)
}

func (x *NullableDeletedAt) GetData() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*NullableDeletedAt_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isNullableDeletedAt_Kind interface {
	isNullableDeletedAt_Kind()
}

type NullableDeletedAt_Null struct {
	Null structpb.NullValue `protobuf:"varint,1,opt,name=null,proto3,enum=google.protobuf.NullValue,oneof"`
}

type NullableDeletedAt_Data struct {
	Data *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*NullableDeletedAt_Null) isNullableDeletedAt_Kind() {}

func (*NullableDeletedAt_Data) isNullableDeletedAt_Kind() {}

type StoreDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *NullableDeletedAt     `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreDataResponse) Reset() {
	*x = StoreDataResponse{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDataResponse) ProtoMessage() {}

func (x *StoreDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDataResponse.ProtoReflect.Descriptor instead.
func (*StoreDataResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{2}
}

func (x *StoreDataResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreDataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreDataResponse) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StoreDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StoreDataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *StoreDataResponse) GetDeletedAt() *NullableDeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type FetchDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataRequest) Reset() {
	*x = FetchDataRequest{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataRequest) ProtoMessage() {}

func (x *FetchDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataRequest.ProtoReflect.Descriptor instead.
func (*FetchDataRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{3}
}

func (x *FetchDataRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FetchDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *NullableDeletedAt     `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDataResponse) Reset() {
	*x = FetchDataResponse{}
	mi := &file_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDataResponse) ProtoMessage() {}

func (x *FetchDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDataResponse.ProtoReflect.Descriptor instead.
func (*FetchDataResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{4}
}

func (x *FetchDataResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FetchDataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchDataResponse) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FetchDataResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FetchDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FetchDataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FetchDataResponse) GetDeletedAt() *NullableDeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type RemoveDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDataRequest) Reset() {
	*x = RemoveDataRequest{}
	mi := &file_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDataRequest) ProtoMessage() {}

func (x *RemoveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDataRequest.ProtoReflect.Descriptor instead.
func (*RemoveDataRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveDataRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDataResponse) Reset() {
	*x = RemoveDataResponse{}
	mi := &file_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDataResponse) ProtoMessage() {}

func (x *RemoveDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDataResponse.ProtoReflect.Descriptor instead.
func (*RemoveDataResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{6}
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsForce       bool                   `protobuf:"varint,6,opt,name=is_force,json=isForce,proto3" json:"is_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_secret_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDataRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDataRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateDataRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateDataRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateDataRequest) GetIsForce() bool {
	if x != nil {
		return x.IsForce
	}
	return false
}

type UpdateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *NullableDeletedAt     `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_secret_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDataResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDataResponse) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateDataResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateDataResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UpdateDataResponse) GetDeletedAt() *NullableDeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type DataRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TypeId        uint32                 `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *NullableDeletedAt     `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRecord) Reset() {
	*x = DataRecord{}
	mi := &file_secret_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRecord) ProtoMessage() {}

func (x *DataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRecord.ProtoReflect.Descriptor instead.
func (*DataRecord) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{9}
}

func (x *DataRecord) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataRecord) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *DataRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DataRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DataRecord) GetDeletedAt() *NullableDeletedAt {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type QueryDataByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeId        uint32                 `protobuf:"varint,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDataByCategoryRequest) Reset() {
	*x = QueryDataByCategoryRequest{}
	mi := &file_secret_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDataByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataByCategoryRequest) ProtoMessage() {}

func (x *QueryDataByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataByCategoryRequest.ProtoReflect.Descriptor instead.
func (*QueryDataByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{10}
}

func (x *QueryDataByCategoryRequest) GetTypeId() uint32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type QueryDataByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretLists   []*DataRecord          `protobuf:"bytes,1,rep,name=secret_lists,json=secretLists,proto3" json:"secret_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDataByCategoryResponse) Reset() {
	*x = QueryDataByCategoryResponse{}
	mi := &file_secret_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDataByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataByCategoryResponse) ProtoMessage() {}

func (x *QueryDataByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataByCategoryResponse.ProtoReflect.Descriptor instead.
func (*QueryDataByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{11}
}

func (x *QueryDataByCategoryResponse) GetSecretLists() []*DataRecord {
	if x != nil {
		return x.SecretLists
	}
	return nil
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x10StoreDataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x7f\n" +
	"\x11NullableDeletedAt\x120\n" +
	"\x04null\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\x04null\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04dataB\x06\n" +
	"\x04kind\"\xfa\x01\n" +
	"\x11StoreDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x18.proto.NullableDeletedAtR\tdeletedAt\"\"\n" +
	"\x10FetchDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x94\x02\n" +
	"\x11FetchDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x18.proto.NullableDeletedAtR\tdeletedAt\"#\n" +
	"\x11RemoveDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x14\n" +
	"\x12RemoveDataResponse\"\xbb\x01\n" +
	"\x11UpdateDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bis_force\x18\x06 \x01(\bR\aisForce\"\xfb\x01\n" +
	"\x12UpdateDataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x18.proto.NullableDeletedAtR\tdeletedAt\"\xab\x02\n" +
	"\n" +
	"DataRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\rR\x06typeId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x18.proto.NullableDeletedAtR\tdeletedAt\"5\n" +
	"\x1aQueryDataByCategoryRequest\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\rR\x06typeId\"S\n" +
	"\x1bQueryDataByCategoryResponse\x124\n" +
	"\fsecret_lists\x18\x01 \x03(\v2\x11.proto.DataRecordR\vsecretLists2\xef\x02\n" +
	"\tDataVault\x12>\n" +
	"\tStoreData\x12\x17.proto.StoreDataRequest\x1a\x18.proto.StoreDataResponse\x12>\n" +
	"\tFetchData\x12\x17.proto.FetchDataRequest\x1a\x18.proto.FetchDataResponse\x12A\n" +
	"\n" +
	"RemoveData\x12\x18.proto.RemoveDataRequest\x1a\x19.proto.RemoveDataResponse\x12A\n" +
	"\n" +
	"UpdateData\x12\x18.proto.UpdateDataRequest\x1a\x19.proto.UpdateDataResponse\x12\\\n" +
	"\x13QueryDataByCategory\x12!.proto.QueryDataByCategoryRequest\x1a\".proto.QueryDataByCategoryResponseB*Z(github.com/smanhack/gophkeeper/api/protob\x06proto3"

var (
	file_secret_proto_rawDescOnce sync.Once
	file_secret_proto_rawDescData []byte
)

func file_secret_proto_rawDescGZIP() []byte {
	file_secret_proto_rawDescOnce.Do(func() {
		file_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)))
	})
	return file_secret_proto_rawDescData
}

var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_secret_proto_goTypes = []any{
	(*StoreDataRequest)(nil),            // 0: proto.StoreDataRequest
	(*NullableDeletedAt)(nil),           // 1: proto.NullableDeletedAt
	(*StoreDataResponse)(nil),           // 2: proto.StoreDataResponse
	(*FetchDataRequest)(nil),            // 3: proto.FetchDataRequest
	(*FetchDataResponse)(nil),           // 4: proto.FetchDataResponse
	(*RemoveDataRequest)(nil),           // 5: proto.RemoveDataRequest
	(*RemoveDataResponse)(nil),          // 6: proto.RemoveDataResponse
	(*UpdateDataRequest)(nil),           // 7: proto.UpdateDataRequest
	(*UpdateDataResponse)(nil),          // 8: proto.UpdateDataResponse
	(*DataRecord)(nil),                  // 9: proto.DataRecord
	(*QueryDataByCategoryRequest)(nil),  // 10: proto.QueryDataByCategoryRequest
	(*QueryDataByCategoryResponse)(nil), // 11: proto.QueryDataByCategoryResponse
	(structpb.NullValue)(0),             // 12: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_secret_proto_depIdxs = []int32{
	12, // 0: proto.NullableDeletedAt.null:type_name -> google.protobuf.NullValue
	13, // 1: proto.NullableDeletedAt.data:type_name -> google.protobuf.Timestamp
	13, // 2: proto.StoreDataResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: proto.StoreDataResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: proto.StoreDataResponse.deleted_at:type_name -> proto.NullableDeletedAt
	13, // 5: proto.FetchDataResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: proto.FetchDataResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: proto.FetchDataResponse.deleted_at:type_name -> proto.NullableDeletedAt
	13, // 8: proto.UpdateDataRequest.updated_at:type_name -> google.protobuf.Timestamp
	13, // 9: proto.UpdateDataResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: proto.UpdateDataResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: proto.UpdateDataResponse.deleted_at:type_name -> proto.NullableDeletedAt
	13, // 12: proto.DataRecord.created_at:type_name -> google.protobuf.Timestamp
	13, // 13: proto.DataRecord.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 14: proto.DataRecord.deleted_at:type_name -> proto.NullableDeletedAt
	9,  // 15: proto.QueryDataByCategoryResponse.secret_lists:type_name -> proto.DataRecord
	0,  // 16: proto.DataVault.StoreData:input_type -> proto.StoreDataRequest
	3,  // 17: proto.DataVault.FetchData:input_type -> proto.FetchDataRequest
	5,  // 18: proto.DataVault.RemoveData:input_type -> proto.RemoveDataRequest
	7,  // 19: proto.DataVault.UpdateData:input_type -> proto.UpdateDataRequest
	10, // 20: proto.DataVault.QueryDataByCategory:input_type -> proto.QueryDataByCategoryRequest
	2,  // 21: proto.DataVault.StoreData:output_type -> proto.StoreDataResponse
	4,  // 22: proto.DataVault.FetchData:output_type -> proto.FetchDataResponse
	6,  // 23: proto.DataVault.RemoveData:output_type -> proto.RemoveDataResponse
	8,  // 24: proto.DataVault.UpdateData:output_type -> proto.UpdateDataResponse
	11, // 25: proto.DataVault.QueryDataByCategory:output_type -> proto.QueryDataByCategoryResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	file_secret_proto_msgTypes[1].OneofWrappers = []any{
		(*NullableDeletedAt_Null)(nil),
		(*NullableDeletedAt_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
