// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: secret_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_secret_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_secret_type_proto_rawDescGZIP(), []int{0}
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_secret_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_secret_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_secret_type_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_secret_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_secret_type_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryListResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_secret_type_proto protoreflect.FileDescriptor

const file_secret_type_proto_rawDesc = "" +
	"\n" +
	"\x11secret_type.proto\x12\x05proto\"\x15\n" +
	"\x13CategoryListRequest\"0\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"G\n" +
	"\x14CategoryListResponse\x12/\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x0f.proto.CategoryR\n" +
	"categories2Y\n" +
	"\fDataCategory\x12I\n" +
	"\x0eListCategories\x12\x1a.proto.CategoryListRequest\x1a\x1b.proto.CategoryListResponseB*Z(github.com/smanhack/gophkeeper/api/protob\x06proto3"

var (
	file_secret_type_proto_rawDescOnce sync.Once
	file_secret_type_proto_rawDescData []byte
)

func file_secret_type_proto_rawDescGZIP() []byte {
	file_secret_type_proto_rawDescOnce.Do(func() {
		file_secret_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_type_proto_rawDesc), len(file_secret_type_proto_rawDesc)))
	})
	return file_secret_type_proto_rawDescData
}

var file_secret_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_secret_type_proto_goTypes = []any{
	(*CategoryListRequest)(nil),  // 0: proto.CategoryListRequest
	(*Category)(nil),             // 1: proto.Category
	(*CategoryListResponse)(nil), // 2: proto.CategoryListResponse
}
var file_secret_type_proto_depIdxs = []int32{
	1, // 0: proto.CategoryListResponse.categories:type_name -> proto.Category
	0, // 1: proto.DataCategory.ListCategories:input_type -> proto.CategoryListRequest
	2, // 2: proto.DataCategory.ListCategories:output_type -> proto.CategoryListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_secret_type_proto_init() }
func file_secret_type_proto_init() {
	if File_secret_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_type_proto_rawDesc), len(file_secret_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_type_proto_goTypes,
		DependencyIndexes: file_secret_type_proto_depIdxs,
		MessageInfos:      file_secret_type_proto_msgTypes,
	}.Build()
	File_secret_type_proto = out.File
	file_secret_type_proto_goTypes = nil
	file_secret_type_proto_depIdxs = nil
}
