syntax = "proto3";

package proto;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/smanhack/gophkeeper/pkg/api";

message StoreDataRequest {
    string name = 1;
    uint32 type = 2;
    bytes payload = 3;
}

message NullableDeletedAt {
    oneof kind {
        google.protobuf.NullValue null = 1;
        google.protobuf.Timestamp data = 2;
    }
}

message StoreDataResponse {
    uint32 id = 1;
    string name = 2;
    uint32 type = 3;
    google.protobuf.Timestamp created_at = 4;
    google.protobuf.Timestamp updated_at = 5;
    NullableDeletedAt deleted_at = 6;
}

message FetchDataRequest {
    int32 id = 1;
}

message FetchDataResponse {
    uint32 id = 1;
    string name = 2;
    uint32 type = 3;
    bytes payload = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp updated_at = 6;
    NullableDeletedAt deleted_at = 7;
}

message RemoveDataRequest {
    uint32 id = 1;
}

message RemoveDataResponse {

}

message UpdateDataRequest {
    uint32 id = 1;
    string name = 2;
    uint32 type = 3;
    bytes payload = 4;
    google.protobuf.Timestamp updated_at = 5;
    bool is_force = 6;
}

message UpdateDataResponse {
    uint32 id = 1;
    string name = 2;
    uint32 type = 3;
    google.protobuf.Timestamp created_at = 4;
    google.protobuf.Timestamp updated_at = 5;
    NullableDeletedAt deleted_at = 6;
}

message DataRecord {
    uint32 id = 1;
    string user_id = 2;
    uint32 type_id = 3;
    string name = 4;
    bytes payload = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
    NullableDeletedAt deleted_at = 8;

}

message QueryDataByCategoryRequest {
    uint32 type_id = 1;
}

message QueryDataByCategoryResponse {
    repeated DataRecord secret_lists = 1;
}

service DataVault {
    rpc StoreData (StoreDataRequest) returns (StoreDataResponse);
    rpc FetchData (FetchDataRequest) returns (FetchDataResponse);
    rpc RemoveData (RemoveDataRequest) returns (RemoveDataResponse);
    rpc UpdateData (UpdateDataRequest) returns (UpdateDataResponse);
    rpc QueryDataByCategory (QueryDataByCategoryRequest) returns (QueryDataByCategoryResponse);
}